language: node_js

node_js:
    - "stable"
    - "8"
    - "6"
    - "4"
    - "0.12"

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^v[0-9].*$/
